export const MAX_CHARS_IN_DISCUSSION_BODY = 18000;
export const MAX_CHARS_IN_DISCUSSION_TITLE = 185;
export const MAX_CHARS_IN_EVENT_DESCRIPTION = 18000;
export const MAX_CHARS_IN_EVENT_TITLE = 185;
export const MAX_CHARS_IN_COMMENT_TEXT = 18000;
export const MAX_CHARS_IN_CHANNEL_DESCRIPTION = 500;
export const MAX_CHARS_IN_CHANNEL_NAME = 50
export const MAX_CHARS_IN_DISPLAY_NAME = 75;